capstone_currency_etl:
  target: dev
  outputs:
    dev:
      account: ${{ secrets.SNOWFLAKE_ORGANIZATION_NAME }}+${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}
      database: CAPSTONE_CURRENCY_DB
      password: ${{ secrets.SNOWFLAKE_PASSWORD }}
      role: ACCOUNTADMIN
      schema: CAPSTONE_CURRENCY_SCHEMA
      threads: 1
      type: snowflake
      user: JOCHENNEUE
      warehouse: CAPSTONE_CURRENCY_WH