capstone_currency_etl:
  target: dev
  outputs:
    dev:
      account: dkpcykd-ai06391
      database: CAPSTONE_CURRENCY_DB
      password: F6NhbBUxhGXpXBa
      role: ACCOUNTADMIN
      schema: CAPSTONE_CURRENCY_SCHEMA
      threads: 1
      type: snowflake
      user: JOCHENNEUE
      warehouse: CAPSTONE_CURRENCY_WH